#! /bin/bash

BUILD_FOLDER="build"
STAGING_FOLDER="tmp"
OUTPUT_FOLDER="out"
BUILD_FILES="kval.js,package.json,lib,node_modules/async,node_modules/debug,node_modules/yargs"
NAME="kval"
COMPANY="Symbolic Logic"
AUTHOR="Jeff H. Parrish"
YEAR=`date +'%Y'`


# rm -rf $BUILD_FOLDER/$STAGING_FOLDER
# rm -rf $BUILD_FOLDER/$OUTPUT_FOLDER

mkdir -p $BUILD_FOLDER/$STAGING_FOLDER
mkdir -p $BUILD_FOLDER/$OUTPUT_FOLDER

cp -f -R lib $BUILD_FOLDER/$STAGING_FOLDER/lib
cp -f package.json $BUILD_FOLDER/$STAGING_FOLDER/package.json
cp -f kval.js $BUILD_FOLDER/$STAGING_FOLDER/kval.js

cd $BUILD_FOLDER/$STAGING_FOLDER
jx install async debug dnode node-lmdb yargs

# will now be in $BUILD_FOLDER
cd ../
rm -f kval.tar.gz

jx package $STAGING_FOLDER/kval.js -name "$NAME" -company "$COMPANY" -author "$AUTHOR" -copyright "$YEAR $AUTHOR" -extract true -native

tar -czf out/kval.tar.gz kval
mv -f kval ... kval/
mv -f kval.jx ... kval/
mv -m kval.jxp ... kval/
