#! /bin/bash

set -x

BUILD_FOLDER="build"
EXCLUDE_FILES="node_modules,db,.git,build,test"
NAME="kval"
COMPANY="Symbolic Logic"
AUTHOR="Jeff H. Parrish"
YEAR=`date +'%Y'`

rm -rf $BUILD_FOLDER
mkdir -p $BUILD_FOLDER

jx package kval.js -name "$NAME" -company "$COMPANY" -author "$AUTHOR" -copyright "$YEAR $AUTHOR" -slim "$EXCLUDE_FILES"

node compile-update-jxp.js

jx compile kval.jxp

tar -czf $BUILD_FOLDER/kval.tar.gz kval

mv kval $BUILD_FOLDER
mv kval.jx $BUILD_FOLDER
mv kval.jxp $BUILD_FOLDER
